/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CreationRouteImport } from './routes/creation'
import { Route as DeplacementRouteImport } from './routes/deplacement'
import { Route as HistoriqueRouteImport } from './routes/historique'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as RechercheRouteImport } from './routes/recherche'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CreationRoute = CreationRouteImport.update({
  id: '/creation',
  path: '/creation',
  getParentRoute: () => rootRouteImport,
} as any)
const DeplacementRoute = DeplacementRouteImport.update({
  id: '/deplacement',
  path: '/deplacement',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriqueRoute = HistoriqueRouteImport.update({
  id: '/historique',
  path: '/historique',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const RechercheRoute = RechercheRouteImport.update({
  id: '/recherche',
  path: '/recherche',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/creation': typeof CreationRoute
  '/deplacement': typeof DeplacementRoute
  '/historique': typeof HistoriqueRoute
  '/parametres': typeof ParametresRoute
  '/recherche': typeof RechercheRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/creation': typeof CreationRoute
  '/deplacement': typeof DeplacementRoute
  '/historique': typeof HistoriqueRoute
  '/parametres': typeof ParametresRoute
  '/recherche': typeof RechercheRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/creation': typeof CreationRoute
  '/deplacement': typeof DeplacementRoute
  '/historique': typeof HistoriqueRoute
  '/parametres': typeof ParametresRoute
  '/recherche': typeof RechercheRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/creation'
    | '/deplacement'
    | '/historique'
    | '/parametres'
    | '/recherche'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/creation'
    | '/deplacement'
    | '/historique'
    | '/parametres'
    | '/recherche'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/creation'
    | '/deplacement'
    | '/historique'
    | '/parametres'
    | '/recherche'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CreationRoute: typeof CreationRoute
  DeplacementRoute: typeof DeplacementRoute
  HistoriqueRoute: typeof HistoriqueRoute
  ParametresRoute: typeof ParametresRoute
  RechercheRoute: typeof RechercheRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creation': {
      id: '/creation'
      path: '/creation'
      fullPath: '/creation'
      preLoaderRoute: typeof CreationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deplacement': {
      id: '/deplacement'
      path: '/deplacement'
      fullPath: '/deplacement'
      preLoaderRoute: typeof DeplacementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historique': {
      id: '/historique'
      path: '/historique'
      fullPath: '/historique'
      preLoaderRoute: typeof HistoriqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recherche': {
      id: '/recherche'
      path: '/recherche'
      fullPath: '/recherche'
      preLoaderRoute: typeof RechercheRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CreationRoute: CreationRoute,
  DeplacementRoute: DeplacementRoute,
  HistoriqueRoute: HistoriqueRoute,
  ParametresRoute: ParametresRoute,
  RechercheRoute: RechercheRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
